[advisories]
version = 2
yanked = "deny"
ignore = [
       "RUSTSEC-2023-0071" # Marvin attack not relevant for local archiving
]

[bans]
deny = [
]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Unicode-3.0",
]
